M48
; DRILL file {KiCad 7.0.7} date Sun Nov  5 22:29:05 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-05T22:29:05-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1160
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1358
%
G90
G05
T1
X4.16Y-3.21
X4.16Y-4.71
X5.41Y-3.21
X5.41Y-4.71
T2
X4.635Y-3.23
X4.935Y-3.23
T0
M30
