M48
; DRILL file {KiCad (6.0.7)} date Tue Mar 21 01:22:46 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-03-21T01:22:46-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.946
%
G90
G05
T1
X80.212Y-47.197
X80.212Y-75.128
X108.148Y-47.197
X108.148Y-75.128
T0
M30
